/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

import app.utility.RoundedBorder;
import java.awt.Dimension;

/**
 *
 * @author ManuelDa
 */
public class panelPregunta extends javax.swing.JPanel {

    /**
     * Creates new form panelPregunta
     */
    public panelPregunta() {
        initComponents();
        
        //Establezco las dimensiones e imagen del botón de eliminar
        Dimension botonEliminarDimension = new Dimension(14, 14);
        utility.SetImageLabel(jLabelBotonEliminar, "src/app/InterfazMobile/Menos_Off.png", botonEliminarDimension);
        
        RoundedBorder roundedBorder = new RoundedBorder(20);
        jPanelFondo.setBorder(roundedBorder);
    }

    public panelPregunta(String pregunta, String respuestaCorrecta, String respuestaIncorrecta1, String respuestaIncorrecta2, String respuestaIncorrecta3) {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPregunta = new javax.swing.JTextField();
        jPanelFondo = new javax.swing.JPanel();
        jLabelBotonEliminar = new javax.swing.JLabel();
        jLabelPregunta = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelPregunta1 = new javax.swing.JLabel();
        jTextFieldPregunta1 = new javax.swing.JTextField();
        jLabelPregunta2 = new javax.swing.JLabel();
        jTextFieldPregunta2 = new javax.swing.JTextField();
        jTextFieldPregunta3 = new javax.swing.JTextField();
        jTextFieldPregunta4 = new javax.swing.JTextField();

        jTextFieldPregunta.setBackground(new java.awt.Color(72, 83, 93));
        jTextFieldPregunta.setColumns(2);
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldPregunta.setText("¿Cuál de estos animales presenta un mayor riesgo de estinción?");
        jTextFieldPregunta.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jTextFieldPregunta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreguntaActionPerformed(evt);
            }
        });

        jPanelFondo.setBackground(new java.awt.Color(26, 41, 54));
        jPanelFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 20, 36), 4, true));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBotonEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/InterfazMobile/Menos_Off.png"))); // NOI18N
        jLabelBotonEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 1, 3));
        jPanelFondo.add(jLabelBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jLabelPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPregunta.setText("Pregunta");
        jPanelFondo.add(jLabelPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 20));

        jTextArea1.setBackground(new java.awt.Color(73, 83, 92));
        jTextArea1.setColumns(3);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("¿Cuales de estos animales presenta un mayor riesgo de extinción?");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 12, 0, 12));
        jPanelFondo.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 40));

        jLabelPregunta1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPregunta1.setText("Respuesta correcta");
        jPanelFondo.add(jLabelPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 20));

        jTextFieldPregunta1.setBackground(new java.awt.Color(72, 83, 93));
        jTextFieldPregunta1.setColumns(2);
        jTextFieldPregunta1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta1.setText("Ajolote");
        jTextFieldPregunta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 12));
        jTextFieldPregunta1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPregunta1ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jTextFieldPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 20));

        jLabelPregunta2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPregunta2.setText("Respuestas incorrectas");
        jPanelFondo.add(jLabelPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 20));

        jTextFieldPregunta2.setBackground(new java.awt.Color(72, 83, 93));
        jTextFieldPregunta2.setColumns(2);
        jTextFieldPregunta2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta2.setText("Koala");
        jTextFieldPregunta2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 12));
        jTextFieldPregunta2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPregunta2ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jTextFieldPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 20));

        jTextFieldPregunta3.setBackground(new java.awt.Color(72, 83, 93));
        jTextFieldPregunta3.setColumns(2);
        jTextFieldPregunta3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta3.setText("Panda");
        jTextFieldPregunta3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 12));
        jTextFieldPregunta3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPregunta3ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jTextFieldPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 20));

        jTextFieldPregunta4.setBackground(new java.awt.Color(72, 83, 93));
        jTextFieldPregunta4.setColumns(2);
        jTextFieldPregunta4.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta4.setText("Capibara");
        jTextFieldPregunta4.setAlignmentY(0.3F);
        jTextFieldPregunta4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 12));
        jTextFieldPregunta4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPregunta4ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jTextFieldPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreguntaActionPerformed

    private void jTextFieldPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPregunta1ActionPerformed

    private void jTextFieldPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPregunta2ActionPerformed

    private void jTextFieldPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPregunta3ActionPerformed

    private void jTextFieldPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPregunta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPregunta4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBotonEliminar;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPregunta1;
    private javax.swing.JLabel jLabelPregunta2;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldPregunta;
    private javax.swing.JTextField jTextFieldPregunta1;
    private javax.swing.JTextField jTextFieldPregunta2;
    private javax.swing.JTextField jTextFieldPregunta3;
    private javax.swing.JTextField jTextFieldPregunta4;
    // End of variables declaration//GEN-END:variables
}
